name: Techbleat Git Action
run-name: Techbleat Git Action
on: [push]
jobs:
    Simple_Test_For_Now:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code from repo
              uses: actions/checkout@v4
            - run: echo "Hello Everyone"
            - run: pwd
            - run: ls

