name: Techbleat Git Action
run-name: Techbleat Git Action
on: [push]
jobs:
    Simple_Test_For_Now:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code from repo
              uses: actions/checkout@v4
            - run: echo "Hello Everyone"
            - run: pwd
            - run: ls

            - name: Set up Terraform to Implement Cloud Infra
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.3.0
            
            - name: Terraform init
              run: terraform init

            - name: Terraform plan
              run: terraform plan

            - name: Terraform apply
              run: terraform apply --auto-approve



